chore: update github action workflows
detra-lab/tsc pull request #19
Opened 2023-06-24 15:12 UTC by rosdb

Resolve #18

2023-06-24 20:22 UTC, giotramu requested changes

2023-06-24 20:22 UTC, giotramu commented on .github/workflows/main.yaml
> +        run: git config --global user.name "detra-bot"
Have you tried to merge the two user configuration steps?

Something like that:

```yaml
- name: Customize GIT user
  run: |
    git config --global user.email "$USER_EMAIL"
    git config --global user.name "detra-bot"
  env:
    USER_EMAIL: ${{ secrets.DETRA_BOT_EMAIL }}
```

2023-06-24 20:22 UTC, giotramu commented on .github/workflows/main.yaml
> +          USER_EMAIL: ${{ secrets.DETRA_BOT_EMAIL }}
Did you configure the env variable `DETRA_BOT_EMAIL` in the organization secrets?

2023-06-26 07:22 UTC, giotramu commented
How about reusing the same workflow for the following repositories?

@detra-lab/eslint-config
@detra-lab/prettier-config
@detra-lab/stylelint-config

[Github Actions - Reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)

Maybe we can do that in another PR? Or do you want to do a spike in this one?

2023-06-26 07:46 UTC, rosdb commented on .github/workflows/main.yaml
> +          USER_EMAIL: ${{ secrets.DETRA_BOT_EMAIL }}
Yes, I did 👍🏻

2023-06-27 13:12 UTC, rosdb commented
> How about reusing the same workflow for the following public repositories?
> 
> @detra-lab/eslint-config @detra-lab/prettier-config @detra-lab/stylelint-config
> 
> [Github Actions - Reusing workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow)
> 
> Maybe we can do that in another PR? Or do you want to do a spike in this one?

@giotramu, I'll do a spike in this one.

2023-06-27 15:23 UTC, giotramu approved these changes

2023-06-27 15:25 UTC, giotramu commented
> @giotramu, I'll do a spike in this one.

To track the activity, I've created a [new task](https://github.com/orgs/detra-lab/projects/2/views/1?pane=issue&itemId=31873309).

2023-06-27 15:26 UTC, merged